# Generated by Django 2.2.2 on 2019-06-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('name', models.CharField(db_column='分类', max_length=20, primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField(auto_now_add=True, db_column='建立时间')),
                ('updatetime', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('title', models.CharField(db_column='标题', max_length=20, primary_key=True, serialize=False)),
                ('context', models.TextField(db_column='教程')),
                ('createtime', models.DateTimeField(auto_now_add=True, db_column='建立时间')),
                ('updatetime', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
                ('classification', models.ForeignKey(db_column='所属分类', on_delete=django.db.models.deletion.CASCADE, to='dhjz.classification')),
            ],
        ),
        migrations.CreateModel(
            name='runtut',
            fields=[
                ('title', models.CharField(db_column='标题', max_length=20, primary_key=True, serialize=False)),
                ('context', models.TextField(db_column='教程')),
                ('createtime', models.DateTimeField(auto_now_add=True, db_column='建立时间')),
                ('updatetime', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
                ('tutorial', models.ForeignKey(db_column='所属标题', on_delete=django.db.models.deletion.CASCADE, to='dhjz.tutorial')),
            ],
        ),
    ]
