# Generated by Django 2.2.5 on 2019-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxwd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jxwd_context',
            name='id',
        ),
        migrations.AlterField(
            model_name='jxwd_context',
            name='title',
            field=models.CharField(db_column='标题', max_length=20, primary_key=True, serialize=False),
        ),
    ]
